-- 17/09/2022
---------------------------------------------------------------------
-- products
INSERT INTO products (description, price, brand, quantity, category,is_active,created_at, updated_at)
VALUES
('Cerveja long neck 330ml - Heineken', 5.39, 'Heineken', 758, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Red Label garrafa 1 Litro - Johnnie Walker', 95.99, 'Johnnie Walker', 722, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Energy Drink lata 250ml - Red Bull', 7.29, 'Red Bull', 456, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 998ml - Smirnoff', 37.99, 'Smirnoff', 911, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês garrafa 1 Litro - White Horse', 80, 'White Horse', 419, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Tenessee garrafa 1 Litro - Jack Daniel''s', 138.9, 'Jack Daniel''s', 909, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético lata 473ml - Monster Energy', 7.39, 'Monster Energy', 225, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês garrafa 1 Litro - Passport', 55.99, 'Passport', 908, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Limão pet 500ml - H2OH', 3.16, 'H2OH', 256, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Budweiser', 4.69, 'Budweiser', 59, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 1 Litro - Seagers', 38.49, 'Seagers', 423, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Uva pet 500ml - Gatorade', 3.99, 'Gatorade', 906, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Limoneto pet 500ml - H2OH', 3.16, 'H2OH', 892, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Limão pet 500ml - Corote', 3.59, 'Corote', 244, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 673, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 200ml - Ducoco', 1.89, 'Ducoco', 203, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice long neck 275ml - Smirnoff', 7.69, 'Smirnoff', 10, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Tangerina pet 500ml - Gatorade', 3.99, 'Gatorade', 831, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Sococo', 6.3, 'Sococo', 182, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça garrafa 965ml - 51', 9.99, '51', 907, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Corona Extra', 5.89, 'Corona Extra', 825, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 1 Litro - Orloff', 31.99, 'Orloff', 47, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1Litro - Puro Coco', 6.99, 'Puro Coco', 256, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Laranja pet 2 Litros - Natural One', 11.29, 'Natural One', 904, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aperitivo garrafa 750ml - Aperol', 47.99, 'Aperol', 779, 'Aperitivo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Maracujá pet 500ml - Gatorade', 3.99, 'Gatorade', 750, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Frutas Cítricas pet 500ml - Gatorade', 3.99, 'Gatorade', 898, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Carménère garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 258, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Adoçada garrafa 910ml - Velho Barreiro', 10.99, 'Velho Barreiro', 423, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água Mineral Natural sem Gás pet 510ml - Nestlé/Pureza Vital', 1.09, 'Nestlé/Pureza Vital', 28, 'Água Mineral', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Concentrado de Maracujá Garrafa 500ml - Maguary', 5.99, 'Maguary', 420, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 750ml - Chilano', 16.99, 'Chilano', 743, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Zero Álcool long neck 330ml - Heineken', 5.69, 'Heineken', 214, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 909, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Mango Loco lata 473ml - Monster Energy', 7.39, 'Monster Energy', 448, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês 12 Anos garrafa 1 Litro - Chivas Regal', 139.99, 'Chivas Regal', 580, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva caixa Leve 15 Pague 12 unidades 25g - Tang', 11.99, 'Tang', 376, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 750ml - Gordon''s', 74.9, 'Gordon''s', 860, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Cream & Marula Fruit garrafa 750ml - Amarula', 104.99, 'Amarula', 905, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1Litro - Maratá', 3.95, 'Maratá', 665, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Energy Drink pet 2 Litros - Baly', 9.49, 'Baly', 967, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Morango pet 500ml - Corote', 3.59, 'Corote', 184, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 900ml - Intencion', 16.99, 'Intencion', 649, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês Finest 8 Anos garrafa 750ml - Ballantine''s', 62.99, 'Ballantine''s', 779, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Seco garrafa 750ml - Chalise', 8.19, 'Chalise', 686, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Kero Coco', 9.25, 'Kero Coco', 329, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Pilsen long neck 355ml - Eisenbahn', 4.29, 'Eisenbahn', 322, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rum Big Apple garrafa 980ml - Bacardí', 31.9, 'Bacardí', 33, 'Rum', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água Mineral Natural com Gás pet 510ml - Nestlé/Pureza Vital', 1.19, 'Nestlé/Pureza Vital', 853, 'Água Mineral', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Stella Artois', 5.29, 'Stella Artois', 566, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça pet 500ml - Corote', 3.36, 'Corote', 682, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais pet 2 Litros - Baly', 9.6, 'Baly', 829, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra Paradise lata 473ml - Monster Energy', 7.39, 'Monster Energy', 346, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Blueberry pet 500ml - Corote', 3.59, 'Corote', 994, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Merlot garrafa 750ml - Chilano', 16.99, 'Chilano', 185, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 750ml - Chilano', 16.99, 'Chilano', 795, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Melancia pet 2 Litros - Baly', 9.6, 'Baly', 907, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 200ml - Kero Coco', 1.99, 'Kero Coco', 686, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Curaçau Blue garrafa 720ml - Stock', 41.49, 'Stock', 55, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Reservado Malbec garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 596, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Khaos lata 473ml - Monster Energy', 7.39, 'Monster Energy', 90, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Pêssego pet 500ml - Corote', 3.59, 'Corote', 762, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Suave garrafa 750ml - Sangue de Boi', 9.79, 'Sangue de Boi', 228, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Maçã Verde pet 2 Litros - Baly', 9.6, 'Baly', 444, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 282, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Laranja pet 180ml - Natural One', 1.95, 'Natural One', 700, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra lata 473ml - Monster Energy', 7.39, 'Monster Energy', 738, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Original garrafa 750ml - Periquita', 44.99, 'Periquita', 572, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel Whisky garrafa 900ml - Master Gold', 14.99, 'Master Gold', 471, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Guaraná lata 350ml - Fruki', 1.85, 'Fruki', 782, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 762, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Heineken', 5.29, 'Heineken', 992, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Piracicaba 966ml - 7 Campos', 6.49, '7 Campos', 444, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Santa Carolina', 20.79, 'Santa Carolina', 562, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva Tinto pet 1,5 Litros - Maguary', 8.89, 'Maguary', 595, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Tenessee Apple garrafa 1Litro - Jack Daniel''s', 136.99, 'Jack Daniel''s', 314, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Tutti Frutti pet 500ml - Corote', 3.59, 'Corote', 588, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 995ml - Rock''s', 29.99, 'Rock''s', 120, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Canelinha pet 500ml - Corote', 3.59, 'Corote', 55, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 237, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Reservado Sauvignon Blanc garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 25, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte lata 473ml - Devassa', 3.49, 'Devassa', 868, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Meio Seco Fino garrafa 750ml - Chilano', 16.99, 'Chilano', 703, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Nacional garrafa 1Litro - Natu Nobilis', 36.99, 'Natu Nobilis', 409, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Chilano', 16.99, 'Chilano', 903, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Uva tetra pak 150ml - Maguary/Fruit Shoot', 1.05, 'Maguary/Fruit Shoot', 97, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Carménère garrafa 750ml - Santa Carolina', 20.79, 'Santa Carolina', 516, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Sweet Red garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 29, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Chopp lata 550ml - Brahma', 4.19, 'Brahma', 717, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Gato Negro', 24, 'Gato Negro', 880, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Ice Limão garrafa 275ml - Skarloff', 4.99, 'Skarloff', 208, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Pêssego tetra pak 1Litro - Maratá', 3.95, 'Maratá', 571, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Polar Export', 3.45, 'Polar Export', 961, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Manga tetra pak 1 Litro - Maratá', 3.95, 'Maratá', 75, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Morango tetra pak 150ml - Maguary/Fruit Shoot', 1.05, 'Maguary/Fruit Shoot', 868, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Malzbier long neck 355ml - Itaipava', 3.95, 'Itaipava', 964, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida de Fruta Adoçada sabor Morango pet 275ml - Maguary/Fruit Shoot', 2.19, 'Maguary/Fruit Shoot', 515, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Irlandês Jameson 8 anos garrafa 750ml - Jameson', 110.99, 'Jameson', 248, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice lata 269ml - Smirnoff', 7.19, 'Smirnoff', 956, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Creme de Cassis garrafa 720ml - Stock', 41.49, 'Stock', 225, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Espanhol garrafa 700ml - 43', 155.9, '43', 64, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Verde Meio Seco garrafa 750ml - Casal Garcia', 41.99, 'Casal Garcia', 339, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1 Litro - Maguary', 3.89, 'Maguary', 183, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva e Maçã pet 2 Litros - Natural One', 13.29, 'Natural One', 188, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink pet 2 Litros - Safadão', 4.5, 'Safadão', 178, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Dragon Ice Tea lata 473ml - Monster Energy', 7.39, 'Monster Energy', 453, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Merlot garrafa 750ml - Gato Negro', 24, 'Gato Negro', 990, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Coco e Açaí pet 2 Litros - Baly', 9.6, 'Baly', 237, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Menta pet 500ml - Corote', 3.59, 'Corote', 30, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês 12 Anos garrafa 750ml - Chivas Regal', 109.9, 'Chivas Regal', 651, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra Violet lata 473ml - Monster Energy', 7.39, 'Monster Energy', 605, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Laranja tetra pak 1 Litro - Marata', 3.95, 'Marata', 118, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Casal Garcia', 41.99, 'Casal Garcia', 340, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 1 Litro - Natasha', 18.99, 'Natasha', 29, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol Seco Fino Oro Tempranillo garrafa 750ml - Pata Negra', 32.99, 'Pata Negra', 823, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Skol', 3.95, 'Skol', 496, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Schin', 2.99, 'Schin', 132, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Maçã Verde vidro 700ml - Monin', 41.99, 'Monin', 986, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Abacaxi tetra pak 1 Litro - Maratá', 3.95, 'Maratá', 103, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Maracujá tetra pak 1Litro - Maratá', 3.95, 'Maratá', 783, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Cranberry vidro 700ml - Monin', 41.99, 'Monin', 319, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Ducoco', 8.49, 'Ducoco', 677, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Marula garrafa 720ml - Stock', 49.99, 'Stock', 21, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Laranja tetra pak 150ml - Maguary/Fruit Shoot', 1.05, 'Maguary/Fruit Shoot', 530, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Canciller', 15.49, 'Canciller', 27, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Maracujá tetra pak 150ml - Maguary/Fruit Shoot', 1.05, 'Maguary/Fruit Shoot', 66, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka pet 966ml - Walesa', 8.99, 'Walesa', 226, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Goiaba tetra pak 1 Litro - Maratá', 3.95, 'Maratá', 410, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet garrafa 750ml - Canciller', 15.49, 'Canciller', 390, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético The Summer Edition sabor Pitaya lata 250ml - Red Bull', 7.29, 'Red Bull', 51, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte lata 473ml - Império', 3.15, 'Império', 928, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Pacific Punch lata 473ml - Monster', 7.39, 'Monster', 708, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Laranja tetra pak 1 Litro - Maguary', 3.89, 'Maguary', 575, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Goiaba tetra pak 200ml - Maratá', 1.25, 'Maratá', 236, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Casillero del Diablo', 41.99, 'Casillero del Diablo', 717, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Casal Garcia', 41.99, 'Casal Garcia', 409, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético lata 473ml - Baly', 4.79, 'Baly', 829, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Chocolate garrafa 720ml - Stock', 41.49, 'Stock', 794, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Tangerina tetra pak 1Litro - Maratá', 3.95, 'Maratá', 828, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope Grenadine vidro 700ml - Monin', 41.99, 'Monin', 519, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Merlot garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 668, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Tangerina vidro 700ml - Monin', 41.99, 'Monin', 435, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja 8g - Clight', 1.15, 'Clight', 141, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Watermelon e Mint garrafa 998ml - Smirnoff/Infusions', 36.99, 'Smirnoff/Infusions', 741, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Trapiche/Vineyards', 36.99, 'Trapiche/Vineyards', 58, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Argentino IX Blend garrafa 750ml - Canciller', 12.49, 'Canciller', 342, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Seco garrafa 750ml - Valpolicella Bolla Classico', 69.99, 'Valpolicella Bolla Classico', 252, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa Leve 1L Pague 750ml - G7', 16.79, 'G7', 502, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Torrontes garrafa 750ml - Canciller', 15.49, 'Canciller', 65, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Strawberry garrafa 995ml - Rock''s', 29.99, 'Rock''s', 625, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1 Litro - Dafruta', 3.39, 'Dafruta', 96, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limonada 8g - Clight', 1.15, 'Clight', 571, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva e Maçã 1,5 Litros - Del Grano', 10, 'Del Grano', 933, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva 8g - Clight', 1.15, 'Clight', 194, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Morango vidro 700ml - Monin', 41.99, 'Monin', 181, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rum Mojito garrafa 980ml - Bacardí', 39.99, 'Bacardí', 566, 'Rum', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Cabernet Sauvignon garrafa 750ml - Salton Classic', 16.49, 'Salton Classic', 868, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 330ml - Ducoco', 3.98, 'Ducoco', 249, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Galitos', 19.49, 'Galitos', 928, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Trapiche Vineyards', 36.99, 'Trapiche Vineyards', 18, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais lata 473ml - Baly', 4.59, 'Baly', 213, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice Limão 275ml - Walesa', 3.09, 'Walesa', 800, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 1Litro - Kutral', 16.75, 'Kutral', 388, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Itaipava', 3.36, 'Itaipava', 391, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Integral de Uva vidro 1,5 Litros - Aliança', 10.99, 'Aliança', 548, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Integral de Uva Tinto garrafa 1,5 Litros - Del Grano', 11.25, 'Del Grano', 48, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Maça Verde lata 473ml - Baly', 4.59, 'Baly', 936, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Seco garrafa 1Litro - Sangue de Boi', 11.99, 'Sangue de Boi', 519, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango 8g - Clight', 1.15, 'Clight', 176, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Coco e Açaí lata 473ml - Baly', 4.59, 'Baly', 935, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Melancia lata 473ml - Baly', 4.59, 'Baly', 352, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink pet 1,98 Litros - Festa Drink', 4.19, 'Festa Drink', 423, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Premium long neck 330ml - Sol', 4.5, 'Sol', 417, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá 8g - Clight', 1.15, 'Clight', 66, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Francês garrafa 750ml - Baron de Ducville', 24.99, 'Baron de Ducville', 407, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Senses long neck 269ml - Skol Beats', 6.49, 'Skol Beats', 198, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Framboesa vidro 700ml - Monin', 41.99, 'Monin', 387, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Pitaya lata 473ml - Baly', 4.59, 'Baly', 553, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Eisenbahn', 4.19, 'Eisenbahn', 573, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi 8g - Clight', 1.15, 'Clight', 67, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Tangerina sachê 8g - Clight', 1.15, 'Clight', 977, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Tierra Alta', 20.99, 'Tierra Alta', 270, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Maracujá vidro 700ml - Monin', 41.99, 'Monin', 76, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva sachê 18g - Tang', 0.99, 'Tang', 285, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte Ipa Maracujá lata 350ml - Baden Baden', 4.25, 'Baden Baden', 819, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Italiano Lambrusco garrafa 750ml - Cavicchioli', 27.99, 'Cavicchioli', 799, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Pêssego, Maça e Laranja pet 900ml - Natural One', 6.85, 'Natural One', 82, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja sachê 18g - Tang', 0.99, 'Tang', 691, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Gentleman garrafa 1 Litro - Jack Daniel''s', 176.9, 'Jack Daniel''s', 787, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Reservado garrafa 750ml - Santa Helena', 21.99, 'Santa Helena', 663, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Suave Pet 1,47 Litros - Monte Carmo', 7.99, 'Monte Carmo', 710, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Crystal', 2.6, 'Crystal', 434, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol San Simón garrafa 750ml - Castillo', 20.99, 'Castillo', 919, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Sevilla garrafa 700ml - Tanqueray', 119.99, 'Tanqueray', 994, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho tinto Chileno Cabernet Sauvignon garrafa 750ml - Tierra Alta', 20.99, 'Tierra Alta', 979, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Sweet Red garrafa 750ml - Casal Garcia', 41.99, 'Casal Garcia', 138, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja Pacote 250g - Promix', 4.5, 'Promix', 466, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva Pacote 250g - Promix', 4.5, 'Promix', 800, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá Pacote 250g - Promix', 4.5, 'Promix', 43, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça pet 807ml - Martelinho', 5.59, 'Martelinho', 558, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português garrafa 750ml - Galitos', 19.49, 'Galitos', 820, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Tangerina pet 2 Litros - Baly', 9.6, 'Baly', 125, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Reserva Malbec garrafa 750ml - Canciller', 23.99, 'Canciller', 838, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Witbier lata 350ml - Baden Baden', 4.25, 'Baden Baden', 149, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 950ml - Walesa', 11.99, 'Walesa', 522, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Original garrafa 750ml - Periquita', 44.99, 'Periquita', 487, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva tetra pak 150ml - Maguary/Fruit Shoot', 1.35, 'Maguary/Fruit Shoot', 458, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Reservado Pedro Jimenez garrafa 750ml - Concha y Toro', 24, 'Concha y Toro', 175, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Passionfruit e Jasmine garrafa 998ml - Smirnoff', 37.99, 'Smirnoff', 275, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Moscatel garrafa 660ml - San Martin', 14.99, 'San Martin', 194, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Lager Leve lata 473ml - Dado Bier', 2.85, 'Dado Bier', 373, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Filtrado Branco garrafa 660ml - Lider', 7.29, 'Lider', 172, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango pacote 25g - Apti', 0.55, 'Apti', 947, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Frisante garrafa 750ml - Monte Paschoal', 16.99, 'Monte Paschoal', 669, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Marula 880ml - Capricho', 9.49, 'Capricho', 472, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja pacote 25g - Apti', 0.55, 'Apti', 399, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Munich long neck 355ml - Spaten', 4.69, 'Spaten', 396, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Cristal lata 350ml - Baden Baden', 4.25, 'Baden Baden', 55, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi sachê 18g - Tang', 0.99, 'Tang', 898, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja GT long neck 269ml - Skol Beats', 6.89, 'Skol Beats', 295, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 750ml - Gato Negro/9 Lives', 34.99, 'Gato Negro/9 Lives', 853, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá sachê 18g - Tang', 0.99, 'Tang', 115, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão pacote 25g - Apti', 0.55, 'Apti', 364, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Gato Negro 9 Lives', 34.99, 'Gato Negro 9 Lives', 75, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Moscatel Rosé garrafa 660ml - San Martin', 14.99, 'San Martin', 150, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão sachê 18g - Tang', 0.99, 'Tang', 266, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi pacote 25g - Apti', 0.55, 'Apti', 121, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol Superior garrafa 750ml - Toro Loco', 37.99, 'Toro Loco', 652, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Maça Verde sem Açúcar lata 473ml - Baly', 4.75, 'Baly', 621, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango sachê 18g - Tang', 0.99, 'Tang', 812, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keep Cooler Piña Colada Long Neck 275ml - Keep Cooler/Classic', 5.49, 'Keep Cooler/Classic', 645, 'Bebidas Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva pacote 25g - Apti', 0.55, 'Apti', 458, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink Green Pet 2 Litros - Safadão', 4.5, 'Safadão', 633, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Suave garrafa 750ml - La Huerta', 20.99, 'La Huerta', 375, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Frisante garrafa 750ml - Monte Paschoal', 16.99, 'Monte Paschoal', 102, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino III Blend Garrafa 1,125 Litros - Canciller', 18.25, 'Canciller', 978, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês Triple Wood garrafa 1 Litro - Grant''s', 81.99, 'Grant''s', 348, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais sem Açúcar lata 473ml - Baly', 4.75, 'Baly', 523, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa Leve 1Litro Pague 750ml - G7', 16.79, 'G7', 662, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Melancia sem Açúcar lata 473ml - Baly', 4.75, 'Baly', 420, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango Pacote 250g - Promix', 4.5, 'Promix', 368, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Budweiser', 4.1, 'Budweiser', 552, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi Pacote 250g - Promix', 4.5, 'Promix', 257, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Blend Adocada Edição Histórica garrafa 600ml - 51', 9.49, '51', 553, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão Pacote 250g - Promix', 4.5, 'Promix', 336, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Salada de Frutas Pacote 250g - Promix', 4.5, 'Promix', 713, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Santa Carolina', 20.79, 'Santa Carolina', 476, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Coffee garrafa 750ml - Amarula', 104.99, 'Amarula', 119, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 1Litro - Kutral', 16.75, 'Kutral', 287, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Lambrusco garrafa 750ml - Cavicchioli', 27.99, 'Cavicchioli', 686, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Manga sachê 18g - Tang', 0.99, 'Tang', 958, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 210ml - Coronita Extra', 4, 'Coronita Extra', 668, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Seco Pet 1,47 Litros - Monte Carmo', 7.99, 'Monte Carmo', 620, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Manga Pacote 250g - Promix', 4.5, 'Promix', 702, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Ipa lata 350ml - Eisenbahn', 4.09, 'Eisenbahn', 398, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Rivaner garrafa 750ml - Black Tower', 41.99, 'Black Tower', 106, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Tangerina sachê 18g - Tang', 0.99, 'Tang', 683, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Guaraná sachê 18g - Tang', 0.99, 'Tang', 477, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Lager Garrafa 600ml - Coruja', 8, 'Coruja', 836, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tequila Branca garrafa 750ml - El Jimador', 115.9, 'El Jimador', 926, 'Tequila', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Alcoólica Mista 800ml - Império Velho', 3.99, 'Império Velho', 713, 'Bebidas Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Colon/Selecto', 23.99, 'Colon/Selecto', 79, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Nacional Demi-Sec garrafa 750ml - Salton Classic', 16.49, 'Salton Classic', 228, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Salada de Frutas pacote 25g - Apti', 0.55, 'Apti', 580, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Quinta de Bons Ventos', 31.99, 'Quinta de Bons Ventos', 874, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Prosecco garrafa 660ml - San Martin', 14.99, 'San Martin', 971, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja Pacote 15g - Fresh', 0.99, 'Fresh', 673, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1Litro - Qualicoco', 6.79, 'Qualicoco', 585, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Rosso garrafa 750ml - Corvo', 58.9, 'Corvo', 489, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Argentino IX Blend Garrafa 1,125 Litros - Canciller', 18.25, 'Canciller', 577, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva Pacote 15g - Fresh', 0.99, 'Fresh', 189, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Guaraná Pacote 15g - Fresh', 0.99, 'Fresh', 288, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Weisse lata 473ml - Patagonia', 5.76, 'Patagonia', 904, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça 807ml - Trago Fino', 5.59, 'Trago Fino', 304, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Colon/Selecto', 23.99, 'Colon/Selecto', 108, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Africano Pinotage Garrafa 750ml - Obikwa', 41.99, 'Obikwa', 939, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Australiano Shiraz garrafa 750ml - Yellow Tail', 41.99, 'Yellow Tail', 752, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Amber Lager lata 473ml - Patagonia', 5.76, 'Patagonia', 844, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 700ml - Gilbeys', 33.99, 'Gilbeys', 84, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Carménère garrafa 750ml - Ventisquero', 38.99, 'Ventisquero', 647, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Ipa lata 473ml - Patagonia', 5.76, 'Patagonia', 473, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Septima', 45.99, 'Septima', 63, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Blend garrafa 750ml - Ventisquero', 38.99, 'Ventisquero', 760, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango Pacote 15g - Fresh', 0.99, 'Fresh', 38, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Cabernet Sauvignon garrafa 750ml - Ventisquero', 38.99, 'Ventisquero', 295, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Africano Suavignon Blanc garrafa 750ml - Nederburg', 34.99, 'Nederburg', 189, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice Xvt Lata 269ml - 51', 4.59, '51', 784, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Bohemian Pilsener lata 473ml - Patagonia', 5.76, 'Patagonia', 421, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Dragon Ice Tea Peach Lata 473ml - Monster Energy', 7.39, 'Monster Energy', 339, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Americano Zinfandel by R. Mondavi garrafa 750ml - Woodbridge', 59.99, 'Woodbridge', 891, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá Pacote 15g - Fresh', 0.99, 'Fresh', 767, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão Pacote 15g - Fresh', 0.99, 'Fresh', 60, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Roble Malbec garrafa 750ml - Trapiche', 44.99, 'Trapiche', 394, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Tierra Alta', 20.99, 'Tierra Alta', 144, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano garrafa 750ml - Codici Puglia', 52.99, 'Codici Puglia', 669, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Reserva garrafa 750ml - Ventisquero', 38.99, 'Ventisquero', 627, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Montepulciano D''Abruzzo garrafa 750ml - Caleo', 37.99, 'Caleo', 465, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Ciconia', 36.99, 'Ciconia', 867, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Colheita Selecionada Regional de Alentejo Seco garrafa 750ml...', 40.99, 'Rapariga da Quinta', 729, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Primitivo Di Manduria Garrafa 750ml - Codici', 79.9, 'Codici', 134, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Verde Garrafa 750ml - Ciconia', 36.99, 'Ciconia', 304, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Australiano Cabernet Sauvignon garrafa 750ml - Yellow Tail', 41.99, 'Yellow Tail', 590, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Primitivo Puglia Garrafa 750ml - Caleo', 44.99, 'Caleo', 744, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Sunset Garrafa 1 Litro - Rock''s', 29.99, 'Rock''s', 457, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Pinot Noir garrafa 750ml - Ventisquero Casablanca', 38.99, 'Ventisquero Casablanca', 840, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Quinta de Bons Ventos', 31.99, 'Quinta de Bons Ventos', 375, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Espanhol Seco Utiel Requena garrafa 750ml - Toro Loco', 37.99, 'Toro Loco', 921, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi Pacote 15g - Fresh', 0.99, 'Fresh', 906, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Ciconia', 36.99, 'Ciconia', 172, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Fresh Garrafa 750ml - Quinta de Bons Ventos', 31.99, 'Quinta de Bons Ventos', 510, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Francês Grande Reserve Bordeaux Supérieur Garrafa 750ml - Calvet', 99.9, 'Calvet', 277, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Garrafa 750ml - Quinta de Bons Ventos', 31.99, 'Quinta de Bons Ventos', 592, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Septima', 45.99, 'Septima', 480, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Demi-sec garrafa 660ml - San Martin', 14.99, 'San Martin', 692, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Chardonnay garrafa 750ml - Ventisquero', 38.99, 'Ventisquero', 78, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 750ml - Tierra Alta', 20.99, 'Tierra Alta', 963, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- customers
INSERT INTO customers (name, cpf, email, address, city, cep, uf, is_active, created_at, updated_at)
VALUES
('Murilo Heitor Monteiro', '05018237007', 'murilo-monteiro93@edepbr.com.br', 'Avenida Generoso Malheiro, 190, Cidade Verde', 'Cuiabá', '78028685', 'MT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aline Alana da Luz', '44435498979', 'alinealanadaluz@uel.br', 'Rua Anísio Azevedo, 522, Treze de Julho', 'Aracaju', '49020248', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gabriela Ayla da Cunha', '76118277230', 'gabriela_dacunha@vnews.com.br', 'Rua São Vicente, 824, Guarituba', 'Piraquara', '83311509', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Melissa Lúcia Melo', '65638911790', 'melissa_lucia_melo@triunfante.com.br', 'Rua Doze, 848, Estância Velha', 'Canoas', '92032714', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elias Jorge da Mata', '72546109588', 'elias_jorge_damata@cebrace.com.br', 'Avenida Francisco Sebrian Madrid, 997, Loteamento Madrid', 'Maringá', '87053515', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cecília Lavínia Cláudia Assunção', '88812989705', 'cecilia_lavinia_assuncao@nipnet.com.br', 'Rua I, 999, Soledade', 'Aracaju', '49089264', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mirella Rosa Costa', '90877430179', 'mirella.rosa.costa@fanger.com.br', 'Largo José Augusto Rocha Lima, 269, Farolândia', 'Aracaju', '49032080', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carla Heloise Cecília da Mota', '69325505126', 'carla_heloise_damota@live.jp', '1ª Travessa da Paz, 305, Sussuarana', 'Salvador', '41214180', 'BA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Alice Maya Ramos', '19204465832', 'alice-ramos75@gabrielresende.com', 'Rua Valdomiro Ferreira Lima, 406, Farolândia', 'Aracaju', '49030730', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Marcelo Leonardo Sebastião da Rocha', '15204488561', 'marcelo_leonardo_darocha@vilasites.com.br', 'Rua Manoel José de Oliveira, 287, Nova Esperança', 'Arapiraca', '57316325', 'AL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Luciana Ester Aragão', '31514918200', 'luciana_ester_aragao@aspxsistemas.com.com.br', 'Rua Colinas, 138, Vila Nova', 'Araguaína', '77818260', 'TO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinicius Augusto da Silva', '11988184177', 'vinicius_augusto_dasilva@vipsaude.com.br', 'Rua F, 162, Sarandi', 'Porto Alegre', '91060500', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fátima Valentina Eliane Farias', '81787671712', 'fatima.valentina.farias@ibest.com.br', 'Rua São Borja, 451, Boa Vista', 'Joinville', '89206400', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Leandro Martin Cavalcanti', '38889905565', 'leandro_cavalcanti@midiasim.com.br', 'Travessa Ademar, 502, Chico Mendes', 'Rio Branco', '69902651', 'AC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Benjamin Raul das Neves', '96739927030', 'benjamin-dasneves97@signa.net.br', 'Vila Amintas Barros, 738, Nova Descoberta', 'Natal', '59075255', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Milena Camila Brito', '15962104439', 'milena_brito@tkk.com.br', 'Rua Olavo Brasil Filho, 368, Jardim Floresta', 'Boa Vista', '69312133', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emanuel Yuri Carvalho', '51900601877', 'emanuel_carvalho@europamotors.com.br', 'Rua José Nóbrega Barbosa, 415, Alto do Mateus', 'João Pessoa', '58090237', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carlos Caleb Silveira', '16032749282', 'carloscalebsilveira@googlemail.com', 'Rua Mestre Vitalino, 496, Curado', 'Jaboatão dos Guararapes', '54220020', 'PE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Levi Guilherme Paulo Rodrigues', '26326438993', 'levi_rodrigues@dominatto.ind.br', 'Rua Demerval Trigueiro do Vale, 660, Araxá', 'Campina Grande', '58404430', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yago Gabriel Rocha', '71459430506', 'yagogabrielrocha@gutembier.com.br', 'Beco Viela da Paz, 110, Nova Contagem', 'Contagem', '32050346', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Olivia Aurora da Rosa', '55472266700', 'olivia.aurora.darosa@contabilidaderangel.com.br', 'Rua D, 444, Olaria', 'Canoas', '92035870', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jéssica Isabella Santos', '64062284057', 'jessica-santos75@openlink.com.br', 'Rua Doutor Antônio José Gomes dos Santos, 214, Fazenda Inglesa', 'Petrópolis', '25725500', 'RJ', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pietro Ruan Sérgio Sales', '56580751061', 'pietro.ruan.sales@moppe.com.br', 'Rua Lagoa Seca, 406, Municípios', 'Santa Rita', '58302430', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Louise Sara Aparício', '15858314503', 'louise-aparicio71@construtoraplaneta.com.br', '2ª Travessa Agostinho Torres, 571, João Paulo', 'São Luís', '65040145', 'MA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lucas Nelson Freitas', '06360970724', 'lucas_nelson_freitas@peopleside.com.br', 'Rua São Luiz, 920, Nova Cidade', 'Boa Vista', '69316252', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mário Sebastião Figueiredo', '03057893767', 'mario-figueiredo94@mx.labinal.com', 'Rua Angélica, 192, Vila Maria Helena', 'Uberaba', '38020010', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Igor Henry Lima', '26757282763', 'igor-lima82@eletroaquila.net', 'Rua Curitiba, 451, Ouro Fino', 'São José dos Pinhais', '83015060', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rosa Antonella Alves', '30616682417', 'rosaantonellaalves@radicigroup.com', 'Rua Coronel Monteiro Baena, 546, Treze de Setembro', 'Boa Vista', '69308110', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Iago Rafael Emanuel Teixeira', '70380151766', 'iago-teixeira88@autbook.com', 'Rua José Augusto Costa, 270, Farolândia', 'Aracaju', '49030470', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emily Elaine Jesus', '33055355989', 'emilyelainejesus@sofisticattomoveis.com.br', 'Rua Rio Jaru, 600, Dom Bosco', 'Ji-Paraná', '76907784', 'RO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kaique Renato Silveira', '80729902170', 'kaique-silveira82@mega.com.br', 'Rua dos Arenques, 612, Jurerê Internacional', 'Florianópolis', '88053462', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bento Igor Bento Rodrigues', '47745009251', 'bentoigorrodrigues@stilomovelaria.com.br', 'Rua do Violoncelo, 729, Castanheira', 'Porto Velho', '76811472', 'RO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Larissa Gabriela Porto', '89657126967', 'larissa.gabriela.porto@deze7.com.br', 'Rua Felipe Camarão, 369, Nossa Senhora da Salete', 'Criciúma', '88815593', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Olivia Emilly da Silva', '19141852508', 'oliviaemillydasilva@zian.com.br', 'Travessa L1 do Provedor, 983, Provedor', 'Santana', '68927408', 'AP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elias Nicolas Drumond', '12446910386', 'elias_nicolas_drumond@outlook.com', 'Rua 23, 607, São José Operário', 'Manaus', '69086240', 'AM', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Helena Nair Figueiredo', '21619168405', 'helena.nair.figueiredo@corpoclinica.com.br', 'Rua Santos, 335, Cidade de Deus', 'Manaus', '69099312', 'AM', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Otávio Benício Raimundo Vieira', '12661227610', 'otavio_benicio_vieira@projetochama.com.br', 'Rua Júlio César de Freitas, 828, Bom Retiro', 'Betim', '32606184', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kevin Bryan Corte Real', '44337444920', 'kevin_cortereal@jsagromecanica.com.br', 'Rua Carlos Alberto Carneiro, 261, Santa Maria da Codipe', 'Teresina', '64012520', 'PI', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Renato Nelson Filipe Farias', '42799320937', 'renato-farias84@yahoo.co.uk', 'Quadra QNL 28 Conjunto G, 197, Taguatinga Norte (Taguatinga)', 'Brasília', '72161807', 'DF', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('César Mateus da Luz', '54617992480', 'cesar-daluz78@advogadosempresariais.com.br', 'Rua Vinte e Nove, 634, Santo Amaro', 'Montes Claros', '39403360', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Osvaldo Lucas Melo', '00929398564', 'osvaldolucasmelo@bessa.net.br', 'Rua das Acácias, 781, Recanto', 'Rio das Ostras', '28890639', 'RJ', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fabiana Valentina Josefa Ferreira', '06195959227', 'fabiana_ferreira@retrosfessa.com.br', 'Rua Vicinal Grécia, 110, Condomínio Privê das Oliveiras', 'Goiânia', '74357240', 'GO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sérgio Elias da Mota', '26648602597', 'sergio_elias_damota@foxtech.com.br', 'Rua Monsenhor Azarias Sobreira, 631, Vicente Pinzon', 'Fortaleza', '60181325', 'CE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fábio Cláudio Roberto Dias', '11498532128', 'fabio.claudio.dias@tuds.com.br', 'Rua Pedro José do Nascimento, 980, Luzia', 'Aracaju', '49046080', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ricardo Geraldo Barbosa', '75155256810', 'ricardo.geraldo.barbosa@digen.com.br', 'Rua Ametista, 266, Ademar Guimarães', 'Redenção', '68552542', 'PA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Andrea Priscila Patrícia Galvão', '81527739139', 'andrea_galvao@jp.ind.br', 'Rua Lourenço Vivan 84, 132, Centro', 'Salto Veloso', '89595970', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Manoel Isaac Diego Freitas', '01513511718', 'manoel.isaac.freitas@pichler.com.br', 'Quadra SQS 111 Bloco C, 744, Asa Sul', 'Brasília', '70374030', 'DF', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tânia Mariana Aragão', '24877269541', 'tania_aragao@debiasi.com.br', 'Passagem José Bonifácio, 513, Julião Ramos', 'Macapá', '68908210', 'AP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bryan Cauã Marcos Vinicius Caldeira', '48194075548', 'bryan.caua.caldeira@ppconsulting.com.br', 'Travessa São Roque do Uruguai, 363, Uruguai', 'Salvador', '40451030', 'BA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Osvaldo Oliver Mendes', '65626758984', 'osvaldoolivermendes@graffiti.net', 'Rua Arapari, 408, Paraviana', 'Boa Vista', '69307235', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rodrigo Bento da Cunha', '18670120062', 'rodrigo.bento.dacunha@creativeinteriores.com.br', 'Rua Poeta José Sampaio, 123, Siqueira Campos', 'Aracaju', '49075470', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Calebe Calebe André Moreira', '47219876769', 'calebe_calebe_moreira@pib.com.br', 'Rua Bezerra Mendes, 728, Centro', 'Mossoró', '59600090', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tomás Martin Duarte', '19528295509', 'tomas.martin.duarte@supercarioca.com', 'Quadra M, 117, Santa Maria da Codipe', 'Teresina', '64012630', 'PI', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yuri Benjamin da Cruz', '54493952059', 'yuri-dacruz85@kimmay.com.br', 'Rua Padre Cícero Batista, 590, Emaús', 'Parnamirim', '59148330', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Andrea Carolina Fabiana Cardoso', '22430125293', 'andrea_carolina_cardoso@outloock.com.br', 'Rua Balbinos, 849, Vila Arizona', 'Itaquaquecetuba', '08575570', 'SP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Felipe Paulo Fernando Viana', '99388751140', 'felipepauloviana@arysta.com.br', 'Rua das Mangueiras, 873, Cristo Rei', 'Várzea Grande', '78118132', 'MT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bruna Heloise Carolina Silva', '13522366565', 'brunaheloisesilva@dkcarmo.com', 'Rua Henrique Coppi, 633, Centro', 'Camboriú', '88340290', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hugo Vicente Carlos Eduardo Moura', '18513380636', 'hugo.vicente.moura@hotmai.com', 'Rua Aracy de Carvalho Guimarães Rosa, 191, Cidade Industrial', 'Curitiba', '81170745', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jaqueline Caroline Sueli Pinto', '17080971632', 'jaqueline_pinto@allurepesquisa.com.br', 'Ladeira Salvador Souza, 274, Centro', 'Guarapari', '29200090', 'ES', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Danilo Victor Bryan Nascimento', '61753312493', 'danilo_victor_nascimento@fojsc.unesp.br', 'Rua Aryo Sardenberg, 756, Boa Esperança', 'Cachoeiro de Itapemirim', '29312419', 'ES', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
