-- 17/09/2022
---------------------------------------------------------------------
-- products
INSERT INTO products (description, price, brand, quantity, category,is_active,created_at, updated_at)
VALUES
('Cerveja long neck 330ml - Heineken', 5.50, 'Heineken', 987, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Red Label garrafa 1 Litro - Johnnie Walker', 97.91, 'Johnnie Walker', 882, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Energy Drink lata 250ml - Red Bull', 7.44, 'Red Bull', 793, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 998ml - Smirnoff', 38.75, 'Smirnoff', 597, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês garrafa 1 Litro - White Horse', 81.60, 'White Horse', 809, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Tenessee garrafa 1 Litro - Jack Daniel''s', 141.68, 'Jack Daniel''s', 199, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético lata 473ml - Monster Energy', 7.54, 'Monster Energy', 203, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês garrafa 1 Litro - Passport', 57.11, 'Passport', 892, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Limão pet 500ml - H2OH', 3.22, 'H2OH', 757, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Budweiser', 4.78, 'Budweiser', 130, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 1 Litro - Seagers', 39.26, 'Seagers', 418, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Uva pet 500ml - Gatorade', 4.07, 'Gatorade', 806, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Limoneto pet 500ml - H2OH', 3.22, 'H2OH', 563, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Limão pet 500ml - Corote', 3.66, 'Corote', 166, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 663, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 200ml - Ducoco', 1.93, 'Ducoco', 101, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice long neck 275ml - Smirnoff', 7.84, 'Smirnoff', 304, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Tangerina pet 500ml - Gatorade', 4.07, 'Gatorade', 943, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Sococo', 6.43, 'Sococo', 367, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça garrafa 965ml - 51', 10.19, '51', 124, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Corona Extra', 6.01, 'Corona Extra', 475, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 1 Litro - Orloff', 32.63, 'Orloff', 832, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1Litro - Puro Coco', 7.13, 'Puro Coco', 574, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Laranja pet 2 Litros - Natural One', 11.52, 'Natural One', 6, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aperitivo garrafa 750ml - Aperol', 48.95, 'Aperol', 322, 'Aperitivo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Maracujá pet 500ml - Gatorade', 4.07, 'Gatorade', 934, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Isotônico sabor Frutas Cítricas pet 500ml - Gatorade', 4.07, 'Gatorade', 776, 'Isotônicos e Hidrotônicos', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Carménère garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 562, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Adoçada garrafa 910ml - Velho Barreiro', 11.21, 'Velho Barreiro', 67, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água Mineral Natural sem Gás pet 510ml - Nestlé/Pureza Vital', 1.11, 'Nestlé/Pureza Vital', 829, 'Água Mineral', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Concentrado de Maracujá Garrafa 500ml - Maguary', 6.11, 'Maguary', 960, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 750ml - Chilano', 17.33, 'Chilano', 895, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Zero Álcool long neck 330ml - Heineken', 5.80, 'Heineken', 210, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 308, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Mango Loco lata 473ml - Monster Energy', 7.54, 'Monster Energy', 956, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês 12 Anos garrafa 1 Litro - Chivas Regal', 142.79, 'Chivas Regal', 949, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva caixa Leve 15 Pague 12 unidades 25g - Tang', 12.23, 'Tang', 92, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 750ml - Gordon''s', 76.40, 'Gordon''s', 792, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Cream & Marula Fruit garrafa 750ml - Amarula', 107.09, 'Amarula', 35, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1Litro - Maratá', 4.03, 'Maratá', 392, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Energy Drink pet 2 Litros - Baly', 9.68, 'Baly', 320, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Morango pet 500ml - Corote', 3.66, 'Corote', 43, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 900ml - Intencion', 17.33, 'Intencion', 12, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês Finest 8 Anos garrafa 750ml - Ballantine''s', 64.25, 'Ballantine''s', 546, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Seco garrafa 750ml - Chalise', 8.35, 'Chalise', 741, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Kero Coco', 9.44, 'Kero Coco', 190, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Pilsen long neck 355ml - Eisenbahn', 4.38, 'Eisenbahn', 396, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rum Big Apple garrafa 980ml - Bacardí', 32.54, 'Bacardí', 972, 'Rum', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água Mineral Natural com Gás pet 510ml - Nestlé/Pureza Vital', 1.21, 'Nestlé/Pureza Vital', 525, 'Água Mineral', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 330ml - Stella Artois', 5.40, 'Stella Artois', 245, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça pet 500ml - Corote', 3.43, 'Corote', 885, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais pet 2 Litros - Baly', 9.79, 'Baly', 396, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra Paradise lata 473ml - Monster Energy', 7.54, 'Monster Energy', 375, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Blueberry pet 500ml - Corote', 3.66, 'Corote', 642, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Merlot garrafa 750ml - Chilano', 17.33, 'Chilano', 534, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 750ml - Chilano', 17.33, 'Chilano', 1000, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Melancia pet 2 Litros - Baly', 9.79, 'Baly', 317, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 200ml - Kero Coco', 2.03, 'Kero Coco', 469, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Curaçau Blue garrafa 720ml - Stock', 42.32, 'Stock', 775, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Reservado Malbec garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 114, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Khaos lata 473ml - Monster Energy', 7.54, 'Monster Energy', 588, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Pêssego pet 500ml - Corote', 3.66, 'Corote', 730, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Suave garrafa 750ml - Sangue de Boi', 9.99, 'Sangue de Boi', 944, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Maçã Verde pet 2 Litros - Baly', 9.79, 'Baly', 823, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 212, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Laranja pet 180ml - Natural One', 1.99, 'Natural One', 429, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra lata 473ml - Monster Energy', 7.54, 'Monster Energy', 907, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Original garrafa 750ml - Periquita', 45.89, 'Periquita', 573, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel Whisky garrafa 900ml - Master Gold', 15.29, 'Master Gold', 643, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refrigerante Guaraná lata 350ml - Fruki', 1.89, 'Fruki', 967, 'Refrigerantes', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 228, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Heineken', 5.40, 'Heineken', 339, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Piracicaba 966ml - 7 Campos', 6.62, '7 Campos', 403, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Santa Carolina', 21.21, 'Santa Carolina', 118, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva Tinto pet 1,5 Litros - Maguary', 9.07, 'Maguary', 186, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Tenessee Apple garrafa 1Litro - Jack Daniel''s', 139.73, 'Jack Daniel''s', 867, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Tutti Frutti pet 500ml - Corote', 3.66, 'Corote', 194, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 995ml - Rock''s', 30.59, 'Rock''s', 54, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Canelinha pet 500ml - Corote', 3.66, 'Corote', 944, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Sauvignon garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 173, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Reservado Sauvignon Blanc garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 773, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte lata 473ml - Devassa', 3.56, 'Devassa', 643, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Meio Seco Fino garrafa 750ml - Chilano', 17.33, 'Chilano', 422, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Nacional garrafa 1Litro - Natu Nobilis', 37.73, 'Natu Nobilis', 813, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Chilano', 17.33, 'Chilano', 1, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Uva tetra pak 150ml - Maguary/Fruit Shoot', 1.07, 'Maguary/Fruit Shoot', 443, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Carménère garrafa 750ml - Santa Carolina', 21.21, 'Santa Carolina', 305, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Sweet Red garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 967, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Chopp lata 550ml - Brahma', 4.27, 'Brahma', 518, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Gato Negro', 24.48, 'Gato Negro', 77, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Ice Limão garrafa 275ml - Skarloff', 5.09, 'Skarloff', 138, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Pêssego tetra pak 1Litro - Maratá', 4.03, 'Maratá', 226, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Polar Export', 3.52, 'Polar Export', 375, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Manga tetra pak 1 Litro - Maratá', 4.03, 'Maratá', 806, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Morango tetra pak 150ml - Maguary/Fruit Shoot', 1.07, 'Maguary/Fruit Shoot', 883, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Malzbier long neck 355ml - Itaipava', 4.03, 'Itaipava', 364, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida de Fruta Adoçada sabor Morango pet 275ml - Maguary/Fruit Shoot', 2.23, 'Maguary/Fruit Shoot', 253, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Irlandês Jameson 8 anos garrafa 750ml - Jameson', 113.21, 'Jameson', 820, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice lata 269ml - Smirnoff', 7.33, 'Smirnoff', 443, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Creme de Cassis garrafa 720ml - Stock', 42.32, 'Stock', 34, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Espanhol garrafa 700ml - 43', 159.02, '43', 235, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Verde Meio Seco garrafa 750ml - Casal Garcia', 42.83, 'Casal Garcia', 595, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1 Litro - Maguary', 3.97, 'Maguary', 383, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva e Maçã pet 2 Litros - Natural One', 13.56, 'Natural One', 645, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink pet 2 Litros - Safadão', 4.59, 'Safadão', 257, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Dragon Ice Tea lata 473ml - Monster Energy', 7.54, 'Monster Energy', 330, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Merlot garrafa 750ml - Gato Negro', 24.48, 'Gato Negro', 1000, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Coco e Açaí pet 2 Litros - Baly', 9.79, 'Baly', 397, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Menta pet 500ml - Corote', 3.66, 'Corote', 788, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês 12 Anos garrafa 750ml - Chivas Regal', 112.10, 'Chivas Regal', 629, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Ultra Violet lata 473ml - Monster Energy', 7.54, 'Monster Energy', 80, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Laranja tetra pak 1 Litro - Marata', 4.03, 'Marata', 146, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Casal Garcia', 42.83, 'Casal Garcia', 51, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 1 Litro - Natasha', 19.37, 'Natasha', 178, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol Seco Fino Oro Tempranillo garrafa 750ml - Pata Negra', 33.65, 'Pata Negra', 729, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Skol', 4.03, 'Skol', 255, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Schin', 3.05, 'Schin', 453, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Maçã Verde vidro 700ml - Monin', 42.83, 'Monin', 272, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Abacaxi tetra pak 1 Litro - Maratá', 4.03, 'Maratá', 388, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Maracujá tetra pak 1Litro - Maratá', 4.03, 'Maratá', 502, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Cranberry vidro 700ml - Monin', 42.83, 'Monin', 214, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1 Litro - Ducoco', 8.66, 'Ducoco', 130, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Marula garrafa 720ml - Stock', 50.99, 'Stock', 567, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Laranja tetra pak 150ml - Maguary/Fruit Shoot', 1.07, 'Maguary/Fruit Shoot', 158, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Canciller', 15.80, 'Canciller', 464, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta Maracujá tetra pak 150ml - Maguary/Fruit Shoot', 1.07, 'Maguary/Fruit Shoot', 528, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka pet 966ml - Walesa', 9.17, 'Walesa', 110, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Goiaba tetra pak 1 Litro - Maratá', 4.03, 'Maratá', 92, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet garrafa 750ml - Canciller', 15.80, 'Canciller', 258, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético The Summer Edition sabor Pitaya lata 250ml - Red Bull', 7.44, 'Red Bull', 146, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte lata 473ml - Império', 3.21, 'Império', 854, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Pacific Punch lata 473ml - Monster', 7.54, 'Monster', 108, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Laranja tetra pak 1 Litro - Maguary', 3.97, 'Maguary', 153, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Goiaba tetra pak 200ml - Maratá', 1.27, 'Maratá', 890, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Casillero del Diablo', 42.83, 'Casillero del Diablo', 868, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Casal Garcia', 42.83, 'Casal Garcia', 426, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético lata 473ml - Baly', 4.89, 'Baly', 453, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Chocolate garrafa 720ml - Stock', 42.32, 'Stock', 508, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Tangerina tetra pak 1Litro - Maratá', 4.03, 'Maratá', 734, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope Grenadine vidro 700ml - Monin', 42.83, 'Monin', 27, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Cabernet Merlot garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 728, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Tangerina vidro 700ml - Monin', 42.83, 'Monin', 401, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja 8g - Clight', 1.17, 'Clight', 788, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Watermelon e Mint garrafa 998ml - Smirnoff/Infusions', 37.73, 'Smirnoff/Infusions', 845, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Trapiche/Vineyards', 37.73, 'Trapiche/Vineyards', 12, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Argentino IX Blend garrafa 750ml - Canciller', 12.74, 'Canciller', 548, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Seco garrafa 750ml - Valpolicella Bolla Classico', 71.39, 'Valpolicella Bolla Classico', 577, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa Leve 1L Pague 750ml - G7', 17.13, 'G7', 897, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Torrontes garrafa 750ml - Canciller', 15.80, 'Canciller', 506, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Strawberry garrafa 995ml - Rock''s', 30.59, 'Rock''s', 246, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Néctar de Fruta sabor Uva tetra pak 1 Litro - Dafruta', 3.46, 'Dafruta', 848, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limonada 8g - Clight', 1.17, 'Clight', 714, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva e Maçã 1,5 Litros - Del Grano', 10.20, 'Del Grano', 595, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva 8g - Clight', 1.17, 'Clight', 226, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Morango vidro 700ml - Monin', 42.83, 'Monin', 121, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rum Mojito garrafa 980ml - Bacardí', 40.79, 'Bacardí', 426, 'Rum', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Cabernet Sauvignon garrafa 750ml - Salton Classic', 16.82, 'Salton Classic', 146, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 330ml - Ducoco', 4.06, 'Ducoco', 446, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Galitos', 19.88, 'Galitos', 832, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Trapiche Vineyards', 37.73, 'Trapiche Vineyards', 869, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais lata 473ml - Baly', 4.68, 'Baly', 990, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice Limão 275ml - Walesa', 3.15, 'Walesa', 407, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 1Litro - Kutral', 17.09, 'Kutral', 774, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Itaipava', 3.43, 'Itaipava', 179, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Integral de Uva vidro 1,5 Litros - Aliança', 11.21, 'Aliança', 673, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco Integral de Uva Tinto garrafa 1,5 Litros - Del Grano', 11.47, 'Del Grano', 490, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Maça Verde lata 473ml - Baly', 4.68, 'Baly', 86, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Nacional Seco garrafa 1Litro - Sangue de Boi', 12.23, 'Sangue de Boi', 253, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango 8g - Clight', 1.17, 'Clight', 476, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Coco e Açaí lata 473ml - Baly', 4.68, 'Baly', 592, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Melancia lata 473ml - Baly', 4.68, 'Baly', 207, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink pet 1,98 Litros - Festa Drink', 4.27, 'Festa Drink', 609, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Premium long neck 330ml - Sol', 4.59, 'Sol', 888, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá 8g - Clight', 1.17, 'Clight', 570, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Francês garrafa 750ml - Baron de Ducville', 25.49, 'Baron de Ducville', 529, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Senses long neck 269ml - Skol Beats', 6.62, 'Skol Beats', 4, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Framboesa vidro 700ml - Monin', 42.83, 'Monin', 683, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético sabor Pitaya lata 473ml - Baly', 4.68, 'Baly', 847, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Eisenbahn', 4.27, 'Eisenbahn', 474, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi 8g - Clight', 1.17, 'Clight', 639, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Tangerina sachê 8g - Clight', 1.17, 'Clight', 950, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Tierra Alta', 21.41, 'Tierra Alta', 888, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Xarope de Maracujá vidro 700ml - Monin', 42.83, 'Monin', 405, 'Xarope', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva sachê 18g - Tang', 1.01, 'Tang', 417, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Puro Malte Ipa Maracujá lata 350ml - Baden Baden', 4.33, 'Baden Baden', 710, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Italiano Lambrusco garrafa 750ml - Cavicchioli', 28.55, 'Cavicchioli', 446, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Pêssego, Maça e Laranja pet 900ml - Natural One', 6.99, 'Natural One', 149, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja sachê 18g - Tang', 1.01, 'Tang', 882, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Americano Gentleman garrafa 1 Litro - Jack Daniel''s', 180.44, 'Jack Daniel''s', 647, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Reservado garrafa 750ml - Santa Helena', 22.43, 'Santa Helena', 2, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Suave Pet 1,47 Litros - Monte Carmo', 8.15, 'Monte Carmo', 349, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Crystal', 2.65, 'Crystal', 72, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol San Simón garrafa 750ml - Castillo', 21.41, 'Castillo', 445, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Sevilla garrafa 700ml - Tanqueray', 122.39, 'Tanqueray', 14, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho tinto Chileno Cabernet Sauvignon garrafa 750ml - Tierra Alta', 21.41, 'Tierra Alta', 39, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Sweet Red garrafa 750ml - Casal Garcia', 42.83, 'Casal Garcia', 641, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja Pacote 250g - Promix', 4.59, 'Promix', 697, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva Pacote 250g - Promix', 4.59, 'Promix', 495, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá Pacote 250g - Promix', 4.59, 'Promix', 259, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça pet 807ml - Martelinho', 5.70, 'Martelinho', 473, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português garrafa 750ml - Galitos', 19.88, 'Galitos', 64, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Tangerina pet 2 Litros - Baly', 9.79, 'Baly', 107, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Reserva Malbec garrafa 750ml - Canciller', 24.47, 'Canciller', 173, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Witbier lata 350ml - Baden Baden', 4.33, 'Baden Baden', 838, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka garrafa 950ml - Walesa', 12.23, 'Walesa', 615, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Original garrafa 750ml - Periquita', 45.89, 'Periquita', 288, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Suco de Uva tetra pak 150ml - Maguary/Fruit Shoot', 1.38, 'Maguary/Fruit Shoot', 418, 'Suco, Néctar e Refresco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Reservado Pedro Jimenez garrafa 750ml - Concha y Toro', 24.48, 'Concha y Toro', 750, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vodka Passionfruit e Jasmine garrafa 998ml - Smirnoff', 38.75, 'Smirnoff', 941, 'Vodka', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Moscatel garrafa 660ml - San Martin', 15.29, 'San Martin', 561, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Lager Leve lata 473ml - Dado Bier', 2.91, 'Dado Bier', 829, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Filtrado Branco garrafa 660ml - Lider', 7.44, 'Lider', 546, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango pacote 25g - Apti', 0.56, 'Apti', 614, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Frisante garrafa 750ml - Monte Paschoal', 17.33, 'Monte Paschoal', 363, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Coquetel sabor Marula 880ml - Capricho', 9.68, 'Capricho', 486, 'Coquetel', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja pacote 25g - Apti', 0.56, 'Apti', 574, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Munich long neck 355ml - Spaten', 4.78, 'Spaten', 704, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Cristal lata 350ml - Baden Baden', 4.33, 'Baden Baden', 685, 'Cerveja Artesanal', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi sachê 18g - Tang', 1.01, 'Tang', 351, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja GT long neck 269ml - Skol Beats', 7.03, 'Skol Beats', 828, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Cabernet Sauvignon garrafa 750ml - Gato Negro/9 Lives', 35.69, 'Gato Negro/9 Lives', 822, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá sachê 18g - Tang', 1.01, 'Tang', 942, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão pacote 25g - Apti', 0.56, 'Apti', 172, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Gato Negro 9 Lives', 35.69, 'Gato Negro 9 Lives', 31, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Moscatel Rosé garrafa 660ml - San Martin', 15.29, 'San Martin', 602, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão sachê 18g - Tang', 1.01, 'Tang', 519, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi pacote 25g - Apti', 0.56, 'Apti', 456, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Espanhol Superior garrafa 750ml - Toro Loco', 38.75, 'Toro Loco', 982, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Maça Verde sem Açúcar lata 473ml - Baly', 4.84, 'Baly', 604, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango sachê 18g - Tang', 1.01, 'Tang', 664, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Keep Cooler Piña Colada Long Neck 275ml - Keep Cooler/Classic', 5.60, 'Keep Cooler/Classic', 150, 'Bebidas Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva pacote 25g - Apti', 0.56, 'Apti', 889, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Composta Drink Green Pet 2 Litros - Safadão', 4.59, 'Safadão', 237, 'Bebidas Não-Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Suave garrafa 750ml - La Huerta', 21.41, 'La Huerta', 847, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Frisante garrafa 750ml - Monte Paschoal', 17.33, 'Monte Paschoal', 928, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino III Blend Garrafa 1,125 Litros - Canciller', 18.61, 'Canciller', 791, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Whisky Escocês Triple Wood garrafa 1 Litro - Grant''s', 83.63, 'Grant''s', 990, 'Whisky', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Frutas Tropicais sem Açúcar lata 473ml - Baly', 4.84, 'Baly', 858, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa Leve 1Litro Pague 750ml - G7', 17.13, 'G7', 816, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Melancia sem Açúcar lata 473ml - Baly', 4.84, 'Baly', 393, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango Pacote 250g - Promix', 4.59, 'Promix', 213, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja lata 473ml - Budweiser', 4.18, 'Budweiser', 486, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi Pacote 250g - Promix', 4.59, 'Promix', 238, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça Blend Adocada Edição Histórica garrafa 600ml - 51', 9.68, '51', 504, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão Pacote 250g - Promix', 4.59, 'Promix', 610, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Salada de Frutas Pacote 250g - Promix', 4.59, 'Promix', 762, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reservado Merlot garrafa 750ml - Santa Carolina', 21.21, 'Santa Carolina', 155, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Licor Coffee garrafa 750ml - Amarula', 107.09, 'Amarula', 960, 'Licor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 1Litro - Kutral', 17.09, 'Kutral', 860, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Lambrusco garrafa 750ml - Cavicchioli', 28.55, 'Cavicchioli', 215, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Manga sachê 18g - Tang', 1.01, 'Tang', 88, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja long neck 210ml - Coronita Extra', 4.08, 'Coronita Extra', 898, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Seco Pet 1,47 Litros - Monte Carmo', 8.15, 'Monte Carmo', 546, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Manga Pacote 250g - Promix', 4.59, 'Promix', 818, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Ipa lata 350ml - Eisenbahn', 4.17, 'Eisenbahn', 353, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Rivaner garrafa 750ml - Black Tower', 42.83, 'Black Tower', 607, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Tangerina sachê 18g - Tang', 1.01, 'Tang', 703, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Guaraná sachê 18g - Tang', 1.01, 'Tang', 957, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Lager Garrafa 600ml - Coruja', 8.16, 'Coruja', 639, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tequila Branca garrafa 750ml - El Jimador', 118.22, 'El Jimador', 148, 'Tequila', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bebida Alcoólica Mista 800ml - Império Velho', 4.07, 'Império Velho', 232, 'Bebidas Alcoólicas', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Colon/Selecto', 24.47, 'Colon/Selecto', 2, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Nacional Demi-Sec garrafa 750ml - Salton Classic', 16.82, 'Salton Classic', 86, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Salada de Frutas pacote 25g - Apti', 0.56, 'Apti', 536, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Quinta de Bons Ventos', 32.63, 'Quinta de Bons Ventos', 371, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Prosecco garrafa 660ml - San Martin', 15.29, 'San Martin', 429, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Laranja Pacote 15g - Fresh', 1.01, 'Fresh', 722, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Água de Coco tetra pak 1Litro - Qualicoco', 6.93, 'Qualicoco', 966, 'Água de Coco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Rosso garrafa 750ml - Corvo', 60.08, 'Corvo', 702, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Argentino IX Blend Garrafa 1,125 Litros - Canciller', 18.61, 'Canciller', 164, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Uva Pacote 15g - Fresh', 1.01, 'Fresh', 816, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Guaraná Pacote 15g - Fresh', 1.01, 'Fresh', 467, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Weisse lata 473ml - Patagonia', 5.88, 'Patagonia', 66, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cachaça 807ml - Trago Fino', 5.70, 'Trago Fino', 613, 'Cachaça', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Colon/Selecto', 24.47, 'Colon/Selecto', 748, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Africano Pinotage Garrafa 750ml - Obikwa', 42.83, 'Obikwa', 701, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Australiano Shiraz garrafa 750ml - Yellow Tail', 42.83, 'Yellow Tail', 639, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Amber Lager lata 473ml - Patagonia', 5.88, 'Patagonia', 718, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin garrafa 700ml - Gilbeys', 34.67, 'Gilbeys', 143, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Carménère garrafa 750ml - Ventisquero', 39.77, 'Ventisquero', 918, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Ipa lata 473ml - Patagonia', 5.88, 'Patagonia', 967, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Malbec garrafa 750ml - Septima', 46.91, 'Septima', 938, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Blend garrafa 750ml - Ventisquero', 39.77, 'Ventisquero', 674, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Morango Pacote 15g - Fresh', 1.01, 'Fresh', 31, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Cabernet Sauvignon garrafa 750ml - Ventisquero', 39.77, 'Ventisquero', 276, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Africano Suavignon Blanc garrafa 750ml - Nederburg', 35.69, 'Nederburg', 3, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ice Xvt Lata 269ml - 51', 4.68, '51', 600, 'Ice', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cerveja Bohemian Pilsener lata 473ml - Patagonia', 5.88, 'Patagonia', 260, 'Cerveja', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Energético Dragon Ice Tea Peach Lata 473ml - Monster Energy', 7.54, 'Monster Energy', 915, 'Energético', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Americano Zinfandel by R. Mondavi garrafa 750ml - Woodbridge', 61.19, 'Woodbridge', 491, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Maracujá Pacote 15g - Fresh', 1.01, 'Fresh', 765, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Limão Pacote 15g - Fresh', 1.01, 'Fresh', 920, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Roble Malbec garrafa 750ml - Trapiche', 45.89, 'Trapiche', 460, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Carménère garrafa 750ml - Tierra Alta', 21.41, 'Tierra Alta', 106, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano garrafa 750ml - Codici Puglia', 54.05, 'Codici Puglia', 863, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Chileno Reserva garrafa 750ml - Ventisquero', 39.77, 'Ventisquero', 129, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Montepulciano D''Abruzzo garrafa 750ml - Caleo', 38.75, 'Caleo', 379, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Ciconia', 37.73, 'Ciconia', 204, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português Colheita Selecionada Regional de Alentejo Seco garrafa 750ml...', 41.81, 'Rapariga da Quinta', 286, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Primitivo Di Manduria Garrafa 750ml - Codici', 81.50, 'Codici', 796, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Verde Garrafa 750ml - Ciconia', 37.73, 'Ciconia', 349, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Australiano Cabernet Sauvignon garrafa 750ml - Yellow Tail', 42.83, 'Yellow Tail', 998, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Italiano Primitivo Puglia Garrafa 750ml - Caleo', 45.89, 'Caleo', 152, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gin Sunset Garrafa 1 Litro - Rock''s', 30.59, 'Rock''s', 369, 'Gin', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Pinot Noir garrafa 750ml - Ventisquero Casablanca', 39.77, 'Ventisquero Casablanca', 627, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Português garrafa 750ml - Quinta de Bons Ventos', 32.63, 'Quinta de Bons Ventos', 708, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Rosé Espanhol Seco Utiel Requena garrafa 750ml - Toro Loco', 38.75, 'Toro Loco', 557, 'Vinho Rosé', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Refresco em Pó sabor Abacaxi Pacote 15g - Fresh', 1.01, 'Fresh', 879, 'Refresco em Pó', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Português garrafa 750ml - Ciconia', 37.73, 'Ciconia', 24, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Fresh Garrafa 750ml - Quinta de Bons Ventos', 32.63, 'Quinta de Bons Ventos', 780, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Francês Grande Reserve Bordeaux Supérieur Garrafa 750ml - Calvet', 101.90, 'Calvet', 231, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Português Garrafa 750ml - Quinta de Bons Ventos', 32.63, 'Quinta de Bons Ventos', 552, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Argentino Cabernet Sauvignon garrafa 750ml - Septima', 46.91, 'Septima', 159, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Espumante Nacional Demi-sec garrafa 660ml - San Martin', 15.29, 'San Martin', 670, 'Espumante', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Tinto Chileno Reserva Chardonnay garrafa 750ml - Ventisquero', 39.77, 'Ventisquero', 876, 'Vinho Tinto', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinho Branco Chileno Sauvignon Blanc garrafa 750ml - Tierra Alta', 21.41, 'Tierra Alta', 154, 'Vinho Branco', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- customers
INSERT INTO customers (name, cpf, email, address, city, cep, uf, is_active, created_at, updated_at)
VALUES
('Murilo Heitor Monteiro', '05018237007', 'murilo-monteiro93@edepbr.com.br', 'Avenida Generoso Malheiro, 190, Cidade Verde', 'Cuiabá', '78028685', 'MT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aline Alana da Luz', '44435498979', 'alinealanadaluz@uel.br', 'Rua Anísio Azevedo, 522, Treze de Julho', 'Aracaju', '49020248', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Gabriela Ayla da Cunha', '76118277230', 'gabriela_dacunha@vnews.com.br', 'Rua São Vicente, 824, Guarituba', 'Piraquara', '83311509', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Melissa Lúcia Melo', '65638911790', 'melissa_lucia_melo@triunfante.com.br', 'Rua Doze, 848, Estância Velha', 'Canoas', '92032714', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elias Jorge da Mata', '72546109588', 'elias_jorge_damata@cebrace.com.br', 'Avenida Francisco Sebrian Madrid, 997, Loteamento Madrid', 'Maringá', '87053515', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cecília Lavínia Cláudia Assunção', '88812989705', 'cecilia_lavinia_assuncao@nipnet.com.br', 'Rua I, 999, Soledade', 'Aracaju', '49089264', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mirella Rosa Costa', '90877430179', 'mirella.rosa.costa@fanger.com.br', 'Largo José Augusto Rocha Lima, 269, Farolândia', 'Aracaju', '49032080', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carla Heloise Cecília da Mota', '69325505126', 'carla_heloise_damota@live.jp', '1ª Travessa da Paz, 305, Sussuarana', 'Salvador', '41214180', 'BA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Alice Maya Ramos', '19204465832', 'alice-ramos75@gabrielresende.com', 'Rua Valdomiro Ferreira Lima, 406, Farolândia', 'Aracaju', '49030730', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Marcelo Leonardo Sebastião da Rocha', '15204488561', 'marcelo_leonardo_darocha@vilasites.com.br', 'Rua Manoel José de Oliveira, 287, Nova Esperança', 'Arapiraca', '57316325', 'AL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Luciana Ester Aragão', '31514918200', 'luciana_ester_aragao@aspxsistemas.com.com.br', 'Rua Colinas, 138, Vila Nova', 'Araguaína', '77818260', 'TO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vinicius Augusto da Silva', '11988184177', 'vinicius_augusto_dasilva@vipsaude.com.br', 'Rua F, 162, Sarandi', 'Porto Alegre', '91060500', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fátima Valentina Eliane Farias', '81787671712', 'fatima.valentina.farias@ibest.com.br', 'Rua São Borja, 451, Boa Vista', 'Joinville', '89206400', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Leandro Martin Cavalcanti', '38889905565', 'leandro_cavalcanti@midiasim.com.br', 'Travessa Ademar, 502, Chico Mendes', 'Rio Branco', '69902651', 'AC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Benjamin Raul das Neves', '96739927030', 'benjamin-dasneves97@signa.net.br', 'Vila Amintas Barros, 738, Nova Descoberta', 'Natal', '59075255', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Milena Camila Brito', '15962104439', 'milena_brito@tkk.com.br', 'Rua Olavo Brasil Filho, 368, Jardim Floresta', 'Boa Vista', '69312133', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emanuel Yuri Carvalho', '51900601877', 'emanuel_carvalho@europamotors.com.br', 'Rua José Nóbrega Barbosa, 415, Alto do Mateus', 'João Pessoa', '58090237', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Carlos Caleb Silveira', '16032749282', 'carloscalebsilveira@googlemail.com', 'Rua Mestre Vitalino, 496, Curado', 'Jaboatão dos Guararapes', '54220020', 'PE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Levi Guilherme Paulo Rodrigues', '26326438993', 'levi_rodrigues@dominatto.ind.br', 'Rua Demerval Trigueiro do Vale, 660, Araxá', 'Campina Grande', '58404430', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yago Gabriel Rocha', '71459430506', 'yagogabrielrocha@gutembier.com.br', 'Beco Viela da Paz, 110, Nova Contagem', 'Contagem', '32050346', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Olivia Aurora da Rosa', '55472266700', 'olivia.aurora.darosa@contabilidaderangel.com.br', 'Rua D, 444, Olaria', 'Canoas', '92035870', 'RS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jéssica Isabella Santos', '64062284057', 'jessica-santos75@openlink.com.br', 'Rua Doutor Antônio José Gomes dos Santos, 214, Fazenda Inglesa', 'Petrópolis', '25725500', 'RJ', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pietro Ruan Sérgio Sales', '56580751061', 'pietro.ruan.sales@moppe.com.br', 'Rua Lagoa Seca, 406, Municípios', 'Santa Rita', '58302430', 'PB', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Louise Sara Aparício', '15858314503', 'louise-aparicio71@construtoraplaneta.com.br', '2ª Travessa Agostinho Torres, 571, João Paulo', 'São Luís', '65040145', 'MA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Lucas Nelson Freitas', '06360970724', 'lucas_nelson_freitas@peopleside.com.br', 'Rua São Luiz, 920, Nova Cidade', 'Boa Vista', '69316252', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Mário Sebastião Figueiredo', '03057893767', 'mario-figueiredo94@mx.labinal.com', 'Rua Angélica, 192, Vila Maria Helena', 'Uberaba', '38020010', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Igor Henry Lima', '26757282763', 'igor-lima82@eletroaquila.net', 'Rua Curitiba, 451, Ouro Fino', 'São José dos Pinhais', '83015060', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rosa Antonella Alves', '30616682417', 'rosaantonellaalves@radicigroup.com', 'Rua Coronel Monteiro Baena, 546, Treze de Setembro', 'Boa Vista', '69308110', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Iago Rafael Emanuel Teixeira', '70380151766', 'iago-teixeira88@autbook.com', 'Rua José Augusto Costa, 270, Farolândia', 'Aracaju', '49030470', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Emily Elaine Jesus', '33055355989', 'emilyelainejesus@sofisticattomoveis.com.br', 'Rua Rio Jaru, 600, Dom Bosco', 'Ji-Paraná', '76907784', 'RO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kaique Renato Silveira', '80729902170', 'kaique-silveira82@mega.com.br', 'Rua dos Arenques, 612, Jurerê Internacional', 'Florianópolis', '88053462', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bento Igor Bento Rodrigues', '47745009251', 'bentoigorrodrigues@stilomovelaria.com.br', 'Rua do Violoncelo, 729, Castanheira', 'Porto Velho', '76811472', 'RO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Larissa Gabriela Porto', '89657126967', 'larissa.gabriela.porto@deze7.com.br', 'Rua Felipe Camarão, 369, Nossa Senhora da Salete', 'Criciúma', '88815593', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Olivia Emilly da Silva', '19141852508', 'oliviaemillydasilva@zian.com.br', 'Travessa L1 do Provedor, 983, Provedor', 'Santana', '68927408', 'AP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Elias Nicolas Drumond', '12446910386', 'elias_nicolas_drumond@outlook.com', 'Rua 23, 607, São José Operário', 'Manaus', '69086240', 'AM', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Helena Nair Figueiredo', '21619168405', 'helena.nair.figueiredo@corpoclinica.com.br', 'Rua Santos, 335, Cidade de Deus', 'Manaus', '69099312', 'AM', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Otávio Benício Raimundo Vieira', '12661227610', 'otavio_benicio_vieira@projetochama.com.br', 'Rua Júlio César de Freitas, 828, Bom Retiro', 'Betim', '32606184', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Kevin Bryan Corte Real', '44337444920', 'kevin_cortereal@jsagromecanica.com.br', 'Rua Carlos Alberto Carneiro, 261, Santa Maria da Codipe', 'Teresina', '64012520', 'PI', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Renato Nelson Filipe Farias', '42799320937', 'renato-farias84@yahoo.co.uk', 'Quadra QNL 28 Conjunto G, 197, Taguatinga Norte (Taguatinga)', 'Brasília', '72161807', 'DF', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('César Mateus da Luz', '54617992480', 'cesar-daluz78@advogadosempresariais.com.br', 'Rua Vinte e Nove, 634, Santo Amaro', 'Montes Claros', '39403360', 'MG', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Osvaldo Lucas Melo', '00929398564', 'osvaldolucasmelo@bessa.net.br', 'Rua das Acácias, 781, Recanto', 'Rio das Ostras', '28890639', 'RJ', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fabiana Valentina Josefa Ferreira', '06195959227', 'fabiana_ferreira@retrosfessa.com.br', 'Rua Vicinal Grécia, 110, Condomínio Privê das Oliveiras', 'Goiânia', '74357240', 'GO', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sérgio Elias da Mota', '26648602597', 'sergio_elias_damota@foxtech.com.br', 'Rua Monsenhor Azarias Sobreira, 631, Vicente Pinzon', 'Fortaleza', '60181325', 'CE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fábio Cláudio Roberto Dias', '11498532128', 'fabio.claudio.dias@tuds.com.br', 'Rua Pedro José do Nascimento, 980, Luzia', 'Aracaju', '49046080', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ricardo Geraldo Barbosa', '75155256810', 'ricardo.geraldo.barbosa@digen.com.br', 'Rua Ametista, 266, Ademar Guimarães', 'Redenção', '68552542', 'PA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Andrea Priscila Patrícia Galvão', '81527739139', 'andrea_galvao@jp.ind.br', 'Rua Lourenço Vivan 84, 132, Centro', 'Salto Veloso', '89595970', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Manoel Isaac Diego Freitas', '01513511718', 'manoel.isaac.freitas@pichler.com.br', 'Quadra SQS 111 Bloco C, 744, Asa Sul', 'Brasília', '70374030', 'DF', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tânia Mariana Aragão', '24877269541', 'tania_aragao@debiasi.com.br', 'Passagem José Bonifácio, 513, Julião Ramos', 'Macapá', '68908210', 'AP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bryan Cauã Marcos Vinicius Caldeira', '48194075548', 'bryan.caua.caldeira@ppconsulting.com.br', 'Travessa São Roque do Uruguai, 363, Uruguai', 'Salvador', '40451030', 'BA', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Osvaldo Oliver Mendes', '65626758984', 'osvaldoolivermendes@graffiti.net', 'Rua Arapari, 408, Paraviana', 'Boa Vista', '69307235', 'RR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Rodrigo Bento da Cunha', '18670120062', 'rodrigo.bento.dacunha@creativeinteriores.com.br', 'Rua Poeta José Sampaio, 123, Siqueira Campos', 'Aracaju', '49075470', 'SE', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Calebe Calebe André Moreira', '47219876769', 'calebe_calebe_moreira@pib.com.br', 'Rua Bezerra Mendes, 728, Centro', 'Mossoró', '59600090', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tomás Martin Duarte', '19528295509', 'tomas.martin.duarte@supercarioca.com', 'Quadra M, 117, Santa Maria da Codipe', 'Teresina', '64012630', 'PI', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Yuri Benjamin da Cruz', '54493952059', 'yuri-dacruz85@kimmay.com.br', 'Rua Padre Cícero Batista, 590, Emaús', 'Parnamirim', '59148330', 'RN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Andrea Carolina Fabiana Cardoso', '22430125293', 'andrea_carolina_cardoso@outloock.com.br', 'Rua Balbinos, 849, Vila Arizona', 'Itaquaquecetuba', '08575570', 'SP', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Felipe Paulo Fernando Viana', '99388751140', 'felipepauloviana@arysta.com.br', 'Rua das Mangueiras, 873, Cristo Rei', 'Várzea Grande', '78118132', 'MT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bruna Heloise Carolina Silva', '13522366565', 'brunaheloisesilva@dkcarmo.com', 'Rua Henrique Coppi, 633, Centro', 'Camboriú', '88340290', 'SC', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hugo Vicente Carlos Eduardo Moura', '18513380636', 'hugo.vicente.moura@hotmai.com', 'Rua Aracy de Carvalho Guimarães Rosa, 191, Cidade Industrial', 'Curitiba', '81170745', 'PR', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Jaqueline Caroline Sueli Pinto', '17080971632', 'jaqueline_pinto@allurepesquisa.com.br', 'Ladeira Salvador Souza, 274, Centro', 'Guarapari', '29200090', 'ES', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Danilo Victor Bryan Nascimento', '61753312493', 'danilo_victor_nascimento@fojsc.unesp.br', 'Rua Aryo Sardenberg, 756, Boa Esperança', 'Cachoeiro de Itapemirim', '29312419', 'ES', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
